### ISSUE TITLE
Does this work for Ubuntu AMIs?

### ISSUE THREAD

**Issue by mrjk05** [widdix/aws-ec2-ssh#10]
Im trying to retro fit this for an ubuntu AMI, however when the script runs import_users.sh it fails as a result of the ubuntu user creation process.

This script works fine for Amazon Linux installs.

Is there any updates for an ubuntu AMI?

**Comment by andreaswittig** [comment]
@mrjk05 If you need Ubuntu, for whatever reason, please update the scripts and send an PR.

**Comment by shinenelson** [comment]
@mrjk05 The script has been updated to support debian-based systems. Maybe you can try again with the updated scripts.
