### ISSUE TITLE
Permission denied (publickey)

### ISSUE THREAD

**Issue by myster-t** [widdix/aws-ec2-ssh#100]
Operating System: Amazon Linux AMI 2017.03
AWS CLI Version: aws-cli/1.11.83 Python/2.7.12 Linux/4.9.32-15.41.amzn1.x86_64 botocore/1.5.46

Followed the README as best as I can:

1) created iam role and instance profile
2) created ec2 with that IAM role
3) added pub key to user
4) cloned project on server
5) ran install.sh and saw new users created in /etc/passwd
6) tried to ssh and got permission denied

I tried to look for log messages but only saw `Dec 13 11:24:03 ip-172-31-17-132 aws-ec2-ssh[20134]: Created new user ....` and no log in attempt log messages

What am I missing? Any ideas on how I can debug this?

Thanks!

**Comment by michaelwittig** [comment]
Hi,

how do you connect to the machine?  If you use the terminal, you can enable verbose mode with `-vvv` on the client side.

**Comment by myster-t** [comment]
Thanks for responding to my ticket.

I ran with -vvv and after the hostkey was found, this was the log output:

debug1: Found key in /Users/mrt/.ssh/known_hosts:159
debug3: send packet: type 21
debug2: set_newkeys: mode 1
debug1: rekey after 134217728 blocks
debug1: SSH2_MSG_NEWKEYS sent
debug1: expecting SSH2_MSG_NEWKEYS
debug3: receive packet: type 21
debug1: SSH2_MSG_NEWKEYS received
debug2: set_newkeys: mode 0
debug1: rekey after 134217728 blocks
debug2: key: /Users/mrt/.ssh/id_rsa (0x0)
debug2: key: /Users/mrt/.ssh/id_dsa (0x0)
debug2: key: /Users/mrt/.ssh/id_ecdsa (0x0)
debug2: key: /Users/mrt/.ssh/id_ed25519 (0x0)
debug3: send packet: type 5
debug3: receive packet: type 6
debug2: service_accept: ssh-userauth
debug1: SSH2_MSG_SERVICE_ACCEPT received
debug3: send packet: type 50
debug3: receive packet: type 51
debug1: Authentications that can continue: publickey
debug3: start over, passed a different list publickey
debug3: preferred publickey,keyboard-interactive,password
debug3: authmethod_lookup publickey
debug3: remaining preferred: keyboard-interactive,password
debug3: authmethod_is_enabled publickey
debug1: Next authentication method: publickey
debug1: Trying private key: /Users/mrt/.ssh/id_rsa
debug3: no such identity: /Users/mrt/.ssh/id_rsa: No such file or directory
debug1: Trying private key: /Users/mrt/.ssh/id_dsa
debug3: no such identity: /Users/mrt/.ssh/id_dsa: No such file or directory
debug1: Trying private key: /Users/mrt/.ssh/id_ecdsa
debug3: no such identity: /Users/mrt/.ssh/id_ecdsa: No such file or directory
debug1: Trying private key: /Users/mrt/.ssh/id_ed25519
debug3: no such identity: /Users/mrt/.ssh/id_ed25519: No such file or directory
debug2: we did not send a packet, disable method
debug1: No more authentication methods to try.
Permission denied (publickey).

would you see anything in this debug output that the server does? i didn't think you'd see the AuthorizedKeysCommand happening on the client side.

i did test the /opt/authorized_keys_command.sh script and ran it as nobody and as root, both worked in returning the pubkey for my user.

**Comment by KusabiSensei** [comment]
What is the command string that you are using with `ssh` to connect? It looks like it is not finding an identity file in the standard places on your client system.

**Comment by myster-t** [comment]
Thanks @KusabiSensei I missed this. You're absolutely correct. I didn't `ssh-add` the correct private key. Thanks for all of your help guys! Works brilliantly now.

**Comment by michaelwittig** [comment]
@KusabiSensei for your help. Much appreciated!
