### ISSUE TITLE
install.sh throwing errors

### ISSUE THREAD

**Issue by subinmath** [widdix/aws-ec2-ssh#102]
Operating System: Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.3 LTS
Release:	16.04
Codename:	xenial
AWS CLI Version: aws-cli/1.14.13 Python/3.5.2 Linux/4.4.0-1041-aws botocore/1.8.17
=================================================================
while running the script  install.sh

root@ip-172-31-88-130:~/aws-ec2-ssh# sh install.sh 
Cloning into 'aws-ec2-ssh'...
remote: Counting objects: 350, done.
remote: Compressing objects: 100% (7/7), done.
remote: Total 350 (delta 1), reused 4 (delta 1), pack-reused 342
Receiving objects: 100% (350/350), 166.58 KiB | 0 bytes/s, done.
Resolving deltas: 100% (177/177), done.
Checking connectivity... done.
install.sh: 161: install.sh: [[: not found
install.sh: 181: install.sh: Syntax error: word unexpected (expecting ")")
root@ip-172-31-88-130:~/aws-ec2-ssh# 

========================================================

**Comment by subinmath** [comment]
Please ignore its working but when i create a new ec2 instance i cannot see my public key added in authorised key

**Comment by KusabiSensei** [comment]
That is by design. SSHD is configured to call the `authorized_keys_command.sh` file, pass it the username that is attempting to sign on, and pull the public key that is stored in IAM for the IAM user.
