### ISSUE TITLE
ssh sudo not working

### ISSUE THREAD

**Issue by subinmath** [widdix/aws-ec2-ssh#110]
Not sure if this is the right place for this issue

Operating System: (Ubuntu)
AWS CLI Version: (aws-cli/1.11.13 Python/3.5.2 Linux/4.4.0-1043-aws botocore/1.4.70
)
Hello

I would tried the script using cloudformation and i could login as the user
But my issue is that i cannot sudo as that user its asking for password.

I would like to allow the user to have sudo access

Can anyone please help out.

**Comment by michaelwittig** [comment]
if you use the install script you can use the `-s` option to determine if users are allowed to use `sudo`. By default, this is not allowed.
The showcase does not allow you to sudo.
