### ISSUE TITLE
Help Required to implement on multiple ec2 instances

### ISSUE THREAD

**Issue by subinmath** [widdix/aws-ec2-ssh#113]
Operating System: (Ubuntu)
AWS CLI Version: (aws-cli/1.11.13 Python/3.5.2 Linux/4.4.0-1043-aws botocore/1.4.70
)
Hello
I implemented this and is working fine for me, if i have n more of instances, How to handle such situations

I used the CF template . 
i created a new ec2 instance but users where not there, do i need to install the script in each instances?

**Comment by michaelwittig** [comment]
Hi @subinmath there are two supported ways of installing the solution as documented here: https://github.com/widdix/aws-ec2-ssh#how-to-integrate-this-system-into-your-environment

yes, you have to install this on each EC2 instance. There are many ways to achieve this:
1) create your own AMI
2) use chef / puppet / ansible
3) Use AWS SSM
4) ...

**Comment by subinmath** [comment]
@michaelwittig 
Thank you for the support and this script has been great help.
