### ISSUE TITLE
Has anyone approached Amazon about moving this into AWS directly?

### ISSUE THREAD

**Issue by aaronlippold** [widdix/aws-ec2-ssh#116]
Action/Feature Request

**Comment by michaelwittig** [comment]
no. But I guess the limitations are too sever: https://github.com/widdix/aws-ec2-ssh#limitations

You can use SSM RunCommand to achieve similar things without the need of SSH at all

**Comment by michaelwittig** [comment]
there hasn't been any progress for a while. feel free to reopen if that changes.
