### ISSUE TITLE
Showcase.yaml not working

### ISSUE THREAD

**Issue by anoora17** [widdix/aws-ec2-ssh#143]
Metadata:
* Operating System: (enter aws ami/ centos 7.6 redhat)
* Installation method: (choose between RPM)
* AWS CLI Version: (exec `aws --version` and aws-cli/1.16.13)

(describe your issue here)
I used the rpm method after uploading the ssk key to the IAM and verified the correct iam permission.
and configured the /etc/aws-ec2-ssh.conf
 ASSUMEROLE='ec2 role that has the permission to get the ssh keys"
IAM_AUTHORIZED_GROUPs='the IAM group that users are in '
SUDOERS_GROUPS= "groupname"

still cannot ssh to the bastion by username

**Comment by michaelwittig** [comment]
We do not support RHEL 7.6 is not supported as clearly stated in the README of this project.

Other people seem to have a problem as well with 7.6 #143
