### ISSUE TITLE
1487 Segmentation fault      /bin/chown -R "${username}:${username}" "$(eval echo ~$username)"

### ISSUE THREAD

**Issue by bantonj** [widdix/aws-ec2-ssh#163]
Metadata:
* Operating System: Amazon Linux 2 (`cpe:2.3:o:amazon:amazon_linux:2`) :: (`Linux 5.4.68-34.125.amzn2.aarch64`)
* Installation method: rpm
* AWS CLI Version: `aws-cli/1.18.147 Python/2.7.18 Linux/5.4.68-34.125.amzn2.aarch64 botocore/1.18.6`

We use this script to add users to our machines while building amis with Packer. We have been getting intermittent segmentation faults with the error message `1487 Segmentation fault      /bin/chown -R "${username}:${username}" "$(eval echo ~$username)"`.  It started around September 27.

**Comment by michaelwittig** [comment]
quick question: Has this ever worked on ARM?

**Comment by bantonj** [comment]
It had been working 100% of the time on arm for the past 9 months, but now this error intermittently occurs.
