### ISSUE TITLE
Create user on the fly?

### ISSUE THREAD

**Issue by fbrnc** [widdix/aws-ec2-ssh#2]
Hi Michael,

excellent [blog post](https://cloudonaut.io/manage-aws-ec2-ssh-access-with-iam/) and thanks for sharing this idea including the code!

I was wondering why you're importing all users (and updating them every 10min). Since you're already running a custom script with `AuthorizedKeysCommand` couldn't you at that point look up if that user exists in IAM and has a public key and only then create it on the fly? (Or will this command fail before ssh even gets to execture this script because the user isn't already there?)
There could be a simple caching mechanism to avoid doing that for every single SSH connection or once the user is created it will not reevaluate the key (and then there could be a cron deleting those keys/user every hour or so forcing the next login after that to reevaluate).

I'm thinking about adopting this idea, but in our use case we have different teams that need access to different sets of servers (with some overlap). I'm thinking of checking the user's groups (with `aws iam list-groups-for-user --user-name ...`) and only allow access if the current server "type" (just a key that we made up) matches one of the user's groups.

Lastly one more thought: Our AWS accounts use email addresses as usernames, but those will be rejected by the `adduser` command. So there probably should be some sanitation before creating the user.

**Comment by michaelwittig** [comment]
Hi and thanks for your feedback.

> Or will this command fail before ssh even gets to execute this script because the user isn't already there?
unfortunately yes. The command is only executed if sshd finds the user locally.

Regarding on-demand user creation: It could be possible to create the users on-demand using PAM but I haven't tried it.

Regarding group management: Your idea sounds fine.

Regarding special characters: I opened issue #3 to fix it.

**Comment by jonleighton** [comment]
Hello, thanks for this. It looks like someone else also had a similar idea with https://github.com/kislyuk/keymaker. Obviously it's a bit more complex being a Python project. I did notice that it can hook into PAM to create the account on the fly, though.

**Comment by michaelwittig** [comment]
@jonleighton That looks promising. 

I guess the interesting parts are:
* https://github.com/kislyuk/keymaker/blob/7d07f8532861421e522fbea9a8a4ada6800d4eff/keymaker/__init__.py#L120
* https://github.com/kislyuk/keymaker/blob/7d07f8532861421e522fbea9a8a4ada6800d4eff/scripts/keymaker-create-account-for-iam-user

**Comment by jonleighton** [comment]
FWIW, I ended up not using keymaker in the end as various things didn't work in my situation, and it was hard to customise. I went with an approach inspired by this project, which meant that it was a lot easier to tailor the solution to my needs. I didn't do the PAM hook at all - in reality we add new users very rarely, so having a wait a minute for the addition to take effect is not a big deal.
