### ISSUE TITLE
v1.0 discussions

### ISSUE THREAD

**Issue by michaelwittig** [widdix/aws-ec2-ssh#28]
So this project got a bit messy because of me not merging stuff fast enough. I would like to get this project back on track. So let's discuss how we continue @shinenelson, @mvanbaak, and @dylansmith  

What we have:

* Multi Account functionality: #22  already as a feature issue here #21 
* Use IAM Groups to manage access: we have quiet a few implementations here
  *#23 Downside, slower because group membership is checked on login, but we don't get into problems with out of date group memberships
  * #19 does not handle changes in the group memberships?
  * @shinenelson import-user-from-groups branch should work similar than 

And we also have a big PR #24  which contains basically all of the above functionality.

My suggestions for v1.0:

* merge Multi Account functionality #22 and close #21 
* merge #23
* close #19 and #24
* fix issue https://github.com/widdix/aws-ec2-ssh/issues/27 (fix is part of #24)
* verify that Documentation is up to date
* verify that iam_ssh_policy.json is up to date
* verify that showcase.yaml is up to date
* verify that install.sh is up to date
* use install.sh in showcase.yaml to not duplicate code
* implement a test that ensures that the available features are working as expected

My suggestion for the future v1.x:

* implement a the better management of local users 
  * uuid
  * local groups
  * shell etc etc
* improve performance of login procedure

What's your opinion?

**Comment by dylansmith** [comment]
I'm fine with whatever you all decide - I've moved to using SSH CA instead so I'm not impacted by the decision.

**Comment by mvanbaak** [comment]
I know my PR is huge. Sorry for that ;-) And I was already expecting it too invasive to be merged as-is, but wanted to be a good citizen and provide it anyways.

The suggestions look good.

If you want I can quickly make a PR for issue #27 alone so it's easier to merge.

The part where the users are deleted if they no longer are member of a group that should access, is something I would personally would like to see in 1.0. I cant remember exactly who's fork I took most of the work from, but I really liked it.

All in all I would say: thanks a lot and good to see you want to take this one further.

**Comment by michaelwittig** [comment]
A PR for #27 would be great 👍🏻

**Comment by mvanbaak** [comment]
Another item that could go on the 1.X list:

* Make a single script which can handle both syncing the users as well as getting the key.

So for example: `ssh-iam-check syncusers` and `ssh-iam-check checksshkey`
The main reason for this is that we start to duplicate code in both sh scripts now (iam assumerole, probably later the group permission thing, and possibly others in the future)

Just a thought I had this morning while resolving conflicts on my outstanding PR's ;-)

**Comment by shinenelson** [comment]
IMO, we should merge #24 and close all the other minor pull requests. #24 has implemented all of them in a single pull request and the code looks consistent. I just did a complete code review and everything should work fine as expected.

**Comment by mvanbaak** [comment]
Thanks for the review and the nice words. As I said the code is taken from some forks and I cleaned up/rewrote the things here and there to make it easier to understand. 

As much as I would like to see it merged its up to @michaelwittig to choose. 

I do however agree that it will be easier to maintain as things are split up in logical functions

**Comment by michaelwittig** [comment]
Ok, I'm fine with the decision to merge #24. I will work on the following items:

[ ] verify that Documentation is up to date
[ ] verify that iam_ssh_policy.json is up to date
[ ] verify that showcase.yaml is up to date
[ ] verify that install.sh is up to date
[ ] use install.sh in showcase.yaml to not duplicate code
[ ] implement a test that ensures that the available features are working as expected
[ ] release v1

**Comment by mvanbaak** [comment]
Cool! Thanks! If I can help with the items let me know :)

**Comment by michaelwittig** [comment]
Could someone review https://github.com/widdix/aws-ec2-ssh/commit/bd9ff5d9cb8f311d7ce63bf850f98e6a69bd06b9 ?

**Comment by mvanbaak** [comment]
Cool, you even created a testsuite! Only suggestion from my side is to comment out the sed lines to set the assumerole var in the showcase so it's consistent with the other optional var sed lines. Left a comment in the commit as well.

Good work. thanks a lot!

**Comment by michaelwittig** [comment]
@mvanbaak I commented on your comment:) https://github.com/widdix/aws-ec2-ssh/commit/bd9ff5d9cb8f311d7ce63bf850f98e6a69bd06b9#commitcomment-21694850

**Comment by michaelwittig** [comment]
v1.0.0 is released :)
