### ISSUE TITLE
v1.x discussions

### ISSUE THREAD

**Issue by michaelwittig** [widdix/aws-ec2-ssh#30]
My suggestion for the future v1.x:

implement a the better management of local users
* [ ] uuid (see #46)
* [x] local groups (implemented by `LOCAL_GROUPS` option)
* [x] shell etc etc (implemented by #39 )
* [ ] Make a single script which can handle both syncing the users as well as getting the key. @mvanbaak here https://github.com/widdix/aws-ec2-ssh/issues/28#issuecomment-290987200

**Comment by michaelwittig** [comment]
as mentioned by @mvanbaak here https://github.com/widdix/aws-ec2-ssh/issues/28#issuecomment-290987200

> Make a single script which can handle both syncing the users as well as getting the key.
So for example: ssh-iam-check syncusers and ssh-iam-check checksshkey
The main reason for this is that we start to duplicate code in both sh scripts now (iam assumerole, probably later the group permission thing, and possibly others in the future)

**Comment by mvanbaak** [comment]
In issue #39 we have the possibility to set another shell by passing the correct arguments to the useradd program. I think this handles point three in the original issue here ;-)
