### ISSUE TITLE
Some inconsistencies when using custom 'home' directories

### ISSUE THREAD

**Issue by uberbrady** [widdix/aws-ec2-ssh#31]
If you use `/etc/login.defs` to set a custom home basedir (instead of `/home`), the system breaks when it tries to sync.

I have a custom home basedir set of `/something/blah` and when the `useradd` call gets invoked, the home directory is correctly created as `/something/blah/${username}`. But then a later `chown` gets invoked, and that seems to be hard-coded to `/home/${username}`.

In my case, I actually *wanted* the users to live in `/home/` so I made a modification to the sync script to do that. I don't know if that's a configurable option you want to enable or not. Seems a little rarely-used, to me. Not a lot of people are gonna want that, I don't think.

But, regardless of that - the bit where it does the `chown` probably ought to read the users "real" home directory, rather than assuming it can do the hardcoding.

Maybe you'd want to use `getent ${username}` and parse out the `:` marks to get their 'real' home? Specifically, I'm seeing this work for me:

```sh
getent passwd $username |cut -d ':' -f 6
```

**Comment by michaelwittig** [comment]
can you check if #33 solves the issue for your case?
otherwise I can use `getent passwd $username |cut -d ':' -f 6`

**Comment by uberbrady** [comment]
I am *so* sorry I haven't had a chance to check this out. I don't think I can do it on the boxes where I'm using it "in anger", but I will try and at least spin up a nano or something with a similar config and give it a quick whirl.

**Comment by uberbrady** [comment]
Crap, no go so far. I had to spin up a t2.nano and just try and run the line on its own, and it doesn't work.

Reading up on BASH expansion, it seems that tilde-expansion happens *before* variable-expansion.

Lemme see if there's another trick we try. maybe a two-step type of thing.

**Comment by uberbrady** [comment]
Well, it looks like the short answer is `eval` - and it's totally fair if you think that Eval is Evil.

But this works - 

```sh
[root@ip-192-168-11-136 testuser]# export homedir=$(eval echo ~$username)
[root@ip-192-168-11-136 testuser]# echo $homedir
/userhome//testuser
```

(don't mind the double-slash problem in there; that's just because I set the default directory dumbly.)

ref: https://serverfault.com/a/134516/180635

**Comment by uberbrady** [comment]
If you want to test this on your own, here's how:

```sh
mkdir /userhome
useradd -D -b /userhome # this sets the new default
adduser testperson
ls -al /userhome/
total 12
drwxr-xr-x  3 root       root       4096 Apr 25 02:05 .
dr-xr-xr-x 26 root       root       4096 Apr 25 02:04 ..
drwx------  2 testperson testperson 4096 Apr 25 02:05 testperson
```

(redacted output to remove usage of ... let's just call them 'nonprofessional' words, shall we?)

**Comment by michaelwittig** [comment]
I guess if we add `eval echo ~$username` we should validate that the incoming IAM username matches to:
```
alphanumeric, plus (+), equal (=), comma (,), period (.), at (@), underscore (_), and hyphen (-).
```
I'm not an expert on this, but I would say than we are safe to eval?

**Comment by mvanbaak** [comment]
As far as I can see that should be safe yes :)

**Comment by michaelwittig** [comment]
I created a new PR #42 to implement this
