### ISSUE TITLE
`./install.sh` requires in-line editing - env vars instead?

### ISSUE THREAD

**Issue by uberbrady** [widdix/aws-ec2-ssh#32]
Right now, if you want to use the `./install.sh` script, you need to directly edit it first. It's not a particularly big deal, but I bet it wouldn't be too hard to instead make it use environment variables instead?

For instead, you'd say something like:

```sh
IAM_AUTHORIZED_GROUPS=admins,devops SUDOERSGROUP=admins ./install.sh
```

Just means you can execute the script as-is, in-place, without editing it.

If this is something you'd be interested in, I'd be happy to put together a quick PR for it.

**Comment by michaelwittig** [comment]
I would even prefer command line arguments. What do you think?

**Comment by uberbrady** [comment]
Sure. Maybe something where if you just run it as is, it yells at you about minimum arguments... maybe a `--help` option or something? I'll ponder.

**Comment by mvanbaak** [comment]
@uberbrady Can you test #35 please? At the moment I'm not able to test it but I think this should work.
