### ISSUE TITLE
Publish to PyPI

### ISSUE THREAD

**Issue by nikolay** [widdix/aws-ec2-ssh#34]
Instead of requiring git and having to `git clone` (i.e. rely on GitHub, which is often DDoS'd), it would be best if you publish this to PyPI so that we can install it via `pip install aws-ec2-ssh`.

**Comment by michaelwittig** [comment]
@nikolay Do you know how publishing to PyPI works?

**Comment by mvanbaak** [comment]
Let me piggybag this issue and state I would like to have an RPM ;-)

**Comment by michaelwittig** [comment]
We now have an RPM
