### ISSUE TITLE
cross-account instructions improvment

### ISSUE THREAD

**Issue by asafcombo** [widdix/aws-ec2-ssh#43]
Hi I found some errors:

should be:
Setup users account -> 3.  Put the **dev aacount**

Also, for multiple accounts, how can one add trust relations for multiple accounts.

Last thing , please add spesific instruction to run the install.sh script with the a cl parameter

**Comment by mvanbaak** [comment]
Thanks for reporting the error. I created a PR that fixes it.

To add more account, in the **users account** find the role you created, go to the 'Trust Relationships' tab, click the 'Edit' button and add more accounts.

Example:
```javascript
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Principal": {
        "AWS": [
          "arn:aws:iam::<DEV ACCOUNT NUMBER>:root",
          "arn:aws:iam::<STAGING ACCOUNT NUMBER>:root",
          "arn:aws:iam::<PRODUCTION ACCOUNT NUMBER>:root"
        ]
      },
      "Action": "sts:AssumeRole"
    }
  ]
}
```
