### ISSUE TITLE
User with number in name always gets shell /sbin/nologin

### ISSUE THREAD

**Issue by trobert2** [widdix/aws-ec2-ssh#49]
Hello,
I have been using this script for a few days and notices that users with names that contain numbers get /sbin/nologin and get added to removed users.

I am wondering if this might be the issue: https://github.com/widdix/aws-ec2-ssh/blob/master/import_users.sh#L164-L169

```
    iam_users=$(get_iam_users | sort | uniq)
    sudo_users=$(get_sudoers_users | sort | uniq)
    local_users=$(get_local_users | sort | uniq)

    intersection=$(echo ${local_users} ${iam_users} | tr " " "\n" | sort | uniq -D | uniq)
    removed_users=$(echo ${local_users} ${intersection} | tr " " "\n" | sort | uniq -u)

```

`local_users` have the local format I.E: robert.at.gmail.com
while `iam_users` have the normal email format. I.E: robert@gmail.com

Thank you

**Comment by michaelwittig** [comment]
@mvanbaak can you have a look at this?

**Comment by mvanbaak** [comment]
Yes. Ill have a look at it

**Comment by uberbrady** [comment]
Okay, just to add in another data-point. I have just *one* of my users - who has no digit in his username! - who mystically seemed to get added to just one server with /sbin/nologin as his shell. I changed his shell back to bash and he could log in normally again.

Maybe eventual consistency bug?

**Comment by mvanbaak** [comment]
@trobert2 is it about usernames with a number or with a special character that's translated by us ?

As you state 'with names that contain numbers' and as example you give 'robert@gmail.com'

**Comment by mvanbaak** [comment]
Created pr that should fix it. I have tested with an iam user 'michiel@this.breaks'

**Comment by trobert2** [comment]
@mvanbaak The special character issue was there for sure. I don't know if the user with a number being added a  `/sbin/nologin` was related. Anyway, thanks for the help!

**Comment by michaelwittig** [comment]
v1.1.1 released

**Comment by mvanbaak** [comment]
Does it make sense to create a test for this? If so, I will need some help with that ;-)

**Comment by michaelwittig** [comment]
I worked with https://github.com/sstephenson/bats before. Any other tools you used for testing bash?
