### ISSUE TITLE
import_iam_users stripping users of groups manually added from *NIX shell

### ISSUE THREAD

**Issue by shinenelson** [widdix/aws-ec2-ssh#56]
If a user is added to a group manually from the *NIX shell, that group is stripped at the next run of the `import_iam_users` `cron`. This is not desirable since we cannot claim `aws-ec2-ssh` to be the ultimate user management utility on the servers.

There are 3 ways to approach this problem : 
1. Do not re-sync the groups of users
2. Use all groups from the user while re-syncing
3. Allow users from specific IAM groups to have local groups. This could complicate the problem since we would have to map each IAM group to their local group, etc.

**Use-case** : 
I use local groups to provide restricted `sudo` access to a subset of users. I cannot give them complete `sudo` access (especially with `NOPASSWD` enabled) and I'll also need to restrict the commands each group is able to run with `sudo`.

**Comment by michaelwittig** [comment]
Does this issue arises when using the `SUDOERSGROUP` config option or `LOCAL_GROUPS` ?

**Comment by mvanbaak** [comment]
I created a pull-request with the fix.

usermod -G adds a user to the given groups, but by default it removes the user from all groups not specified in the list. Adding the -a flag means the user is added to the specified groups, and if the user is member of other groups, it will stay member of those groups.

**Comment by mvanbaak** [comment]
From the manual page:

```
       -a, --append
           Add the user to the supplementary group(s). Use only with the -G option.
```

```
       -G, --groups GROUP1[,GROUP2,...[,GROUPN]]]
           A list of supplementary groups which the user is also a member of. Each group is separated from the next by a comma, with no intervening whitespace. The groups are subject to the same restrictions as the group given with the -g option.

           If the user is currently a member of a group which is not listed, the user will be removed from the group. This behaviour can be changed via the -a option, which appends the user to the current supplementary group list.
```

**Comment by michaelwittig** [comment]
releases as 1.1.2
