### ISSUE TITLE
Multiple sudoers groups

### ISSUE THREAD

**Issue by nikolay** [widdix/aws-ec2-ssh#59]
First, the current variable `SUDOERSGROUP` has inconsistent naming (along with `ASSUMEROLE`) - words are not delimited by an `_`.

Second, there are use cases in which we want more than a single group having sudo access.

Deprecate `SUDOERSGROUP` for `SUDOERS_GROUPS` and, until removed, `SUDOERS_GROUPS` can default to `SUDOERSGROUP`.

**Comment by obenziane2** [comment]
Great job guys! Has this being fixed ?

**Comment by mvanbaak** [comment]
I can have a look at this tomorrow. @michaelwittig if you want you can assign to me. Today I wont have time for it.

**Comment by michaelwittig** [comment]
For some reasons, GitHub don't let me assign you to the issue... but feel assigned :)

**Comment by mvanbaak** [comment]
Probably because I'm not part of the widdix team, makes sense.
I've some code done but have to test it today. If tested I'll create a pr.

**Comment by mvanbaak** [comment]
Sorry, switching jobs takes a bit more than I was anticipating. Did not forget about this.

**Comment by michaelwittig** [comment]
no worries. you contributed quiet some time in the past to make the project better. Thanks for this!

**Comment by mvanbaak** [comment]
PR created and tested in vagrant. Ready to be reviewed and merged.
