### ISSUE TITLE
issue when removing the user from the IAM group

### ISSUE THREAD

**Issue by obenziane2** [widdix/aws-ec2-ssh#60]
Found an issue when removing the user from the IAM group. If I remove the user from the group, it does not ssh in which is great and  it works. But if I put him back to the IAM group (running /opt/import_users.sh manually), it can't login.
The fix i did is to remove the user from the system, `usedel user1`... and remove his directory.

I found out that it jail the user to `/sbin/nologin`  
`user1:x:504:505::/home/user1:/sbin/nologin`

**Comment by michaelwittig** [comment]
Can you confirm that the user was actually deleted before it was created again?
Question is: Was the user deleted or is the deletion broken.

**Comment by mvanbaak** [comment]
If the user is still present on the system, but with a shell of h/sbin/nologin, the userdel command failed.
This is probably because there were still processes running for this user.

We can force delete a user, but this line in the manpage scares me a little:

```
Note: This option is dangerous and may leave your system in an inconsistent state.
```

**Comment by michaelwittig** [comment]
maybe in https://github.com/widdix/aws-ec2-ssh/blob/master/import_users.sh#L156

```
/usr/bin/pkill -15 -u "${1}"
/usr/bin/pkill -9 -u "${1}"
```

?

**Comment by obenziane2** [comment]
Yeah, that's the issue, i had to remove that line, somehow it prevents from executing the delete command on AWS linux instance

**Comment by mvanbaak** [comment]
Good plan, but I'd put a sleep in the middle to give applications some time to shutdown (be a nice admin ;-) )

Let me cook up a PR

**Comment by mvanbaak** [comment]
Since we make very sure all processes have gotten the kill signal, we can delete the user with -f as it's safe to do now.
Just to make sure we delete the user, I added the -f flag.

If you feel uncomfortable with it, tell me and I can delete it again.
