### ISSUE TITLE
Add an option to grab groups and keys from GitHub

### ISSUE THREAD

**Issue by nikolay** [widdix/aws-ec2-ssh#63]
I'm not sure if every SSH user has an IAM account, but we all have pretty well-secured GitHub accounts. How about adding an option to grab groups and users from GitHub, too?

Maybe we need an adapter with implementations for IAM and GitHub and keep the rest of the code universal.

Let's not forget that AWS CLI comes with JMESPath, which I like more than jq, so, GitHub can be used via curl and JMESPath without requiring client libraries or other packages.

Just an idea. I may git this a try if you give me a blessing.

**Comment by michaelwittig** [comment]
The idea sounds good. But I would like to keep this project small in scope. But feel free to fork the project. I'm happy to put a link in the README.

**Comment by nikolay** [comment]
I don't think it would be more code. At the end of the day, the command to get the list of teams, users in a team, and each user's SSH key isn't more than just a few lines of Bash. As you know, most of your code is not specific to IAM, but doing generic stuff for local user management.

**Comment by nikolay** [comment]
Okay, let me give it a try and then you can decide.

**Comment by siavashs** [comment]
I have developed a modular solution for our company which supports both AWS and GitHub, it's in testing phase now and hopefully will be released under an opensource license soon.

**Comment by michaelwittig** [comment]
@siavashs let us know when it is released. I'm interested!

**Comment by michaelwittig** [comment]
there hasn't been any progress for a while. feel free to reopen if that changes.
