### ISSUE TITLE
Feature request - Google Auth

### ISSUE THREAD

**Issue by jcajkovic** [widdix/aws-ec2-ssh#71]
Hi guys,

I'm wondering if there is a place to add here also creation of .google_authenticator file during user creation process - the content of the file could be the parameter from AWS Parameter Store (encrypted string option).

The Role you are assuming needs only default KMS decrypt and parameter read permission.

Thanks for answers.

**Comment by michaelwittig** [comment]
Can you explain me what the use case is here? What are you trying to solve?

**Comment by jcajkovic** [comment]
Hi, well just to have multi factor authentication out of box with the Google Authenticator on SSH with creation of the users. I understand if this is out of scope from this project, it is just the idea to improve overall security with IAM. (btw I like what you did here) 

In fact I can do that as another cronjob script to check all the iam-synced-users and get the file from different source and and create it. However integration with this module would be much more elegant solution.

**Comment by michaelwittig** [comment]
What other pieces are needed to make it work? Just putting the file in the home directory doesn't seem to be enough?

**Comment by jcajkovic** [comment]
well you need to have configured SSH and installed google-auth part on linux instance.

here is nice tutorial: https://www.digitalocean.com/community/tutorials/how-to-set-up-multi-factor-authentication-for-ssh-on-ubuntu-16-04

**Comment by michaelwittig** [comment]
Since this solution is about "Manage AWS EC2 SSH access with IAM" I would also argue that your proposal is out of scope. 

But there are other ideas that want to expand the scope pf the project like #63 

So if there is a group of people who wants to expand the project scope we can discuss this and I'm happy to add additional core contributors to the project.

**Comment by jcajkovic** [comment]
Hi Michael, thanks for your input, I will solve the issue in separate script. I completely understand your opinion on this.

you can close this issue as Not to be implemented ;-)
