### ISSUE TITLE
Issue with doing an IAM request with every login

### ISSUE THREAD

**Issue by omahonyb** [widdix/aws-ec2-ssh#73]
Is there a way to get this to not perform the IAM aws cli command if it finds a .ss/authorized_keys entry?

The reason I ask is we use Ansible to build out environments, and currently it is causing intermittent issues with timeouts on ssh, specially if we are running the playbooks against a large number of instances. The playbooks are using the local ec2-user, so it would really be benificial to us, if when it finds a working key, it doesn't go off to IAM.

Regards

B

**Comment by michaelwittig** [comment]
the ec2-user should not be an IAM user. if the user is not found in IAM, ssh will fall back to authorized_keys , so ec2-user should always work?

You talk about timeouts on ssh. Is it possible that this has nothing to do with the iam call?

**Comment by omahonyb** [comment]
Apologies, I wrote that yesterday evening while very tired, and probably did not convey my message very well.

The ec2-user is not an IAM user, it is a local user, and works fine.
The timeouts are not so much timeouts as noticeable slow downs during the ansible playbook runs [or during an IAM user login]

What I am looking to do is have the script check if the ec2-user has its authorized_keys in place, and if it does, use that instead of trying to check IAM, which is where the slow down is. Failing that is there a clean way to except specific users from the IAM lookup?

Other than the slow login for ec2-user, this is a great piece of work, an much appreciated :D

**Comment by michaelwittig** [comment]
I don't think this is possible:

From the sshd docs:
```
AuthorizedKeysCommand
Specifies a program to be used for lookup of the user's public keys. The program will be invoked with its first argument the name of the user being authorized, and should produce on standard output AuthorizedKeys lines (see AUTHORIZED_KEYS in sshd(8)). By default (or when set to the empty string) there is no AuthorizedKeysCommand run. If the AuthorizedKeysCommand does not successfully authorize the user, authorization falls through to the AuthorizedKeysFile. Note that this option has an effect only with PubkeyAuthentication turned on.
```

which means that AuthorizedKeysCommand runs first, after that the AuthorizedKeysFile is checked. You can not reverse that order.

**Comment by omahonyb** [comment]
Thanks mate, I thought that was the case after my own research, but had hoped that you had better in depth knowledge :P. Only way I see is putting an if statement in the script to abort if it is finds a authorized_keys file for the user. Ill have a look myself next week. Friday means it is out. :D
