### ISSUE TITLE
DONOTSYNC not set to 1 on install

### ISSUE THREAD

**Issue by askainet** [widdix/aws-ec2-ssh#75]
The sed substitution command is not setting DONOTSYNC=1 when installing using RPM

A working and standard sed command could be:

`sed -i 's/DONOTSYNC=0/DONOTSYNC=1/g' ${RPM_BUILD_ROOT}%{_sysconfdir}/aws-ec2-ssh.conf`

**Comment by michaelwittig** [comment]
could you test with this RPM: https://s3-eu-west-1.amazonaws.com/widdix-aws-ec2-ssh-releases-eu-west-1/aws-ec2-ssh-1.2.1-1.el7.centos.noarch.rpm

**Comment by askainet** [comment]
Works great, thanks!
