### ISSUE TITLE
Strip special characters from sudoers.d filenames

### ISSUE THREAD

**Issue by bradpeczka** [widdix/aws-ec2-ssh#8]
Per [http://www.sudo.ws/man/1.8.13/sudoers.man.html](http://www.sudo.ws/man/1.8.13/sudoers.man.html):
> sudo will read each file in `/etc/sudoers.d`, skipping file names that end in ‘~’ or contain a ‘.’ character to avoid causing problems with package manager or editor temporary/backup files.

This has an unintended side effect for IAM users that follow a first name.lastname naming convention - assuming John Smith has a username of john.smith, `import_user.sh` creates a file of `/etc/sudoers.d/john.smith` which is then ignored by sudo, and the user is prompted for a password when sudoing that (generally) doesn't exist.

Ideally, `import_user.sh` should be modified to remove all non-alphanumeric characters from the names of any files created under `/etc/sudoers.d`, while retaining the actual IAM username within the sudoers.d file.

**Comment by michaelwittig** [comment]
first of all: good catch :)

allowed characters for IAM usernames are:
> alphanumeric, including the following common characters: plus (+), equal (=), comma (,), period (.), at (@), underscore (_), and hyphen (-).

So the `~` is not a problem.

What about the case where we have two users in IAM like this:
* michaelwittig
* michael.wittig

This will end in a problem if we only remove the `.`. I suggest to not remove the `.` character, but replace it with a character that is not allowed in IAM usernames at all. I suggest `$`

What do you think?

**Comment by bradpeczka** [comment]
I think the use of the `$` character would cause other issues given it's commonly used to define variables in scripts.

Perhaps consider the `^` character instead?

**Comment by bradpeczka** [comment]
It's also worth noting that this appears to be a moot issue if pull request #7 from @bobziuchkovski is merged. 

Thanks also for the project and effort... my team is only just starting to explore AWS, but we're looking to do it right from day 1, and SSH/IAM integration is top of our list!

**Comment by michaelwittig** [comment]
I now replace the `.` with an ` ` should be less confusing thatn `$` or `^`
