### ISSUE TITLE
CentOS support

### ISSUE THREAD

**Issue by michaelwittig** [widdix/aws-ec2-ssh#84]
from @nicholascowan

#83  breaks functionality on CENTOS7 because it's checking for init.d scripts and doesn't take into account systemd, the restart method should be systemctl restart sshd.

This causes script to throw an error since ssh.service is not found, and would break in any cloudformation scripts.

**Comment by KusabiSensei** [comment]
There are actually two things that need to be considered here. One is the use of `systemd`. The other is SELinux being turned on with default policies.

It looks like there may be a way around that without needing the end user to disable SELinux or put SELinux into permissive mode. SELinux provides booleans that can tune the base policy from CentOS or Red Hat, and turning on the NIS boolean would allow for auth programs (like PAM or sshd) to make outbound calls to get user information.

I'm currently testing a patch in the installer script to allow this. Once that is done, it may be worth looking into making that change in the RPM itself.

**Comment by KusabiSensei** [comment]
The systemd code that is in #99 and got updated in #107 should support CentOS, along with the SELinux portions of #99 

We should be able to close out this issue. Perhaps now with the fix, we could add CentOS to the Showcase.

**Comment by michaelwittig** [comment]
I prepare a test case to ensure that CentOS is always working...
