### ISSUE TITLE
The script is not working on some instances. When i check I havent had AWS and PIP installed I have installed and ran the script but after 10 mins when cron job runs the aws and pip commands were not running. Can I run 

### ISSUE THREAD

**Issue by mtadepalli69** [widdix/aws-ec2-ssh#86]

**Comment by michaelwittig** [comment]
could you check your issue title/description? looks like a few characters are missing?

besides that, can you check if there are any errors in `/var/log/cron`

**Comment by mtadepalli69** [comment]
I am getting this error when i went through the logs in /var/spool/mail/root

**/opt/import_users.sh: line 63: aws: command not found**

This EC2 instance where I am running the script has been launched using EC2 Container Service where it comes with a role automatically and I have added the policy to it and also added the role in authorized_commands.sh and I have manually installed pip, aws-amitools and aws-apitools. So I am getting the issues.

**Comment by michaelwittig** [comment]
you are using the ECS optimized Amazon Linux which does not have the AWS CLI installed. We only support Amazon Linux and Ubuntu.

Make sure to install the AWS CLI and have the PATH set correctly int he cronjob file.

**Comment by mtadepalli69** [comment]
I have installed AWS CLI and also set the path correctly in .bash_profile file. Do i need to set correctly in some other file ? Cronjob file means doing crontab -e works ?

**Comment by mtadepalli69** [comment]
To be exact where to check like in which script does this cron job is set ? Sorry for asking on small things since I am new to this I couldn't figure out. Thanks in Advance.

**Comment by michaelwittig** [comment]
cron does not use bash_profile. 

try this command in your shell:
```
which aws
```

and use this full path in the cronjob.

**Comment by mtadepalli69** [comment]
I have checked the file from /etc/cron.d/
This is what i have under the above path for import_users file


**SHELL=/bin/bash
PATH=/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/sbin:/opt/aws/bin
MAILTO=root
HOME=/
*/10 * * * * root /opt/import_users.sh**

aws --version
aws-cli/1.11.158 Python/2.7.12 Linux/4.9.43-17.38.amzn1.x86_64 botocore/1.7.16

Added path to .bash_profile file 
PATH=~/.local/bin:$HOME/bin:$PATH

**Comment by mtadepalli69** [comment]
Hi,

I have updated the cronjob with the full path that i have got after executing "which aws" but still after cron job gets executed, I have seen this error

 **/opt/import_users.sh: line 63: aws: command not found**

Can you help me please
