### ISSUE TITLE
RPM link needs to be updated.

### ISSUE THREAD

**Issue by Mistawes** [widdix/aws-ec2-ssh#89]
I was trying to install the 1.1 RPM from the README, but noticed the cron wasn't included. Poked around the URL and found there's a 1.4 version, which seems to include it. Might wanna update the URL in the README **_EDIT:_** I found it under releases just now.

Correct URL:
https://s3-eu-west-1.amazonaws.com/widdix-aws-ec2-ssh-releases-eu-west-1/aws-ec2-ssh-1.4.0-1.el7.centos.noarch.rpm

Fantastic tool btw, very grateful to have it!

**Comment by anshul0915** [comment]
How you able to get pm download fro s3 i am getting error in my cfn can you help
