### ISSUE TITLE
Error when calling GetGroup operation

### ISSUE THREAD

**Issue by kenske** [widdix/aws-ec2-ssh#93]
I'm trying to get the multi-account setup working according to the example on the README. Whenever I run the install script on an instance in the dev account, I get this:

```bash
module.iam-ssh-install.aws_instance.example (remote-exec): An error occurred (IncompleteSignature) when calling the GetGroup operation: Credential must have exactly 5 slash-delimited elements, e.g. keyid/date/region/service/term, got '<key removed>/20171023/us-east-1/iam/aws4_request'
```
The key has slashes in it. Does the script need to escape the value? Any ideas on how to fix this?

**Comment by michaelwittig** [comment]
* Which operating system are you using?
* What's the version of the AWS CLI (run `aws --version`)

**Comment by kenske** [comment]
Here's what I'm running:
AWS Version: `aws-cli/1.11.13 Python/3.5.2+ Linux/4.8.0-41-generic botocore/1.4.70`
OS: Ubuntu 16.10

**Comment by kenske** [comment]
Turns out the parameters in this line were in the wrong order:
https://github.com/widdix/aws-ec2-ssh/blob/master/import_users.sh#L62

Not sure if you want to add a dependency, but this is how I fixed it:
https://github.com/widdix/aws-ec2-ssh/pull/95
